# Generated by Django 3.0.5 on 2020-04-26 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200425_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='valor_mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parametros'),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parametros'),
        ),
    ]
