# Generated by Django 3.0.5 on 2020-04-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200426_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor_hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Valor_mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='mensalista',
            name='valor_mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Valor_mes'),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Valor_hora'),
        ),
        migrations.DeleteModel(
            name='Parametros',
        ),
    ]
