# Generated by Django 3.0.5 on 2020-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200426_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='valor_mes',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='Valor_mes',
        ),
    ]
