# Generated by Django 3.0.5 on 2020-04-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200426_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valor_hora',
            new_name='Parametros',
        ),
    ]
