# Generated by Django 3.0.5 on 2020-04-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200426_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
